version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "risk:dependencies"

  - package-ecosystem: "npm"
    directory: "/workspace"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "risk:dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "risk:dependencies"
      - "risk:ci"
